"use client"

import { useState, useEffect } from "react"
import { BookOpen, FileDown, Loader2, RefreshCw } from "lucide-react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import remarkBreaks from "remark-breaks"
import mermaid from "mermaid"
import { API_BASE_URL } from "@/lib/api"

mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  securityLevel: 'loose',
})

const MermaidChart = ({ code }: { code: string }) => {
  const [svg, setSvg] = useState<string>('')
  
  useEffect(() => {
    let isMounted = true;
    const renderChart = async () => {
      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`
        const { svg } = await mermaid.render(id, code)
        if (isMounted) setSvg(svg)
      } catch (err) {
        console.error("Mermaid error", err)
      }
    }
    renderChart()
    return () => { isMounted = false; }
  }, [code])

  if (!svg) return <div className="p-4 flex items-center justify-center animate-pulse bg-muted/50 rounded-lg">Rendering diagram...</div>

  return <div className="my-6 flex justify-center bg-card p-4 rounded-xl border border-border overflow-x-auto" dangerouslySetInnerHTML={{ __html: svg }} />
}

export function ArchitectureReport({ projectId }: { projectId: string }) {
  const [content, setContent] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function fetchReport() {
    if (!projectId) return
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`${API_BASE_URL}/api/projects/${projectId}/file/ARCHITECTURE.md`)
      if (!res.ok) {
        if (res.status === 404) {
          throw new Error("ARCHITECTURE.md not found. Ensure the project was scaffolded with OmniLead.")
        }
        throw new Error("Failed to fetch architecture report.")
      }
      const data = await res.json()
      setContent(data.content)
    } catch (err: any) {
      console.error("Error fetching report:", err)
      setError(err.message || "Failed to load report.")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchReport()
  }, [projectId])

  const handlePrint = () => {
    window.print()
  }

  if (!projectId) {
    return (
      <div className="flex h-full items-center justify-center text-muted-foreground">
        Select a project to view its architecture report.
      </div>
    )
  }

  return (
    <div className="flex h-full flex-col p-6 overflow-hidden">
      <div className="mb-6 flex items-center justify-between no-print">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-foreground flex items-center gap-2">
            <BookOpen className="size-6 text-primary" />
            Architecture PRD
          </h1>
          <p className="text-sm text-muted-foreground">
            Project blueprint and system architecture automatically generated by OmniLead.
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={fetchReport}
            disabled={loading}
            className="flex items-center gap-2 rounded-md border border-border bg-transparent px-3 py-1.5 text-sm font-medium text-foreground transition-colors hover:bg-secondary disabled:opacity-50"
          >
            <RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
          <button
            onClick={handlePrint}
            disabled={!content || loading}
            className="flex items-center gap-2 rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
          >
            <FileDown className="size-4" />
            Download PDF
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto rounded-xl border border-border bg-card shadow-sm scrollable-print">
        {loading ? (
          <div className="flex h-64 items-center justify-center">
            <Loader2 className="size-8 animate-spin text-primary" />
          </div>
        ) : error ? (
          <div className="flex h-64 flex-col items-center justify-center gap-3 text-destructive">
            <BookOpen className="size-8 opacity-50" />
            <p className="text-sm font-medium">{error}</p>
          </div>
        ) : content ? (
          <div className="p-8 md:p-12">
            <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none print:prose-black print:text-black">
              <ReactMarkdown
                remarkPlugins={[remarkGfm, remarkBreaks]}
                components={{
                  code(props) {
                    const {children, className, node, ...rest} = props
                    const match = /language-(\w+)/.exec(className || '')
                    if (match && match[1] === 'mermaid') {
                      return <MermaidChart code={String(children).replace(/\n$/, '')} />
                    }
                    return <code {...rest} className={className}>{children}</code>
                  }
                }}
              >
                {content}
              </ReactMarkdown>
            </div>
          </div>
        ) : (
          <div className="flex h-64 flex-col items-center justify-center gap-3 text-muted-foreground">
            <BookOpen className="size-8 opacity-20" />
            <p className="text-sm">No report available.</p>
          </div>
        )}
      </div>
    </div>
  )
}
